---
- hosts: localhost
  gather_facts: False
  roles:
    - { role: kargo-defaults}
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"]}

- hosts: temp 
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  remote_user: vagrant
  vars:
    # Need to disable pipelining for bootstrap-os as some systems have requiretty in sudoers set, which makes pipelining
    # fail. bootstrap-os fixes this on these systems, so in later plays it can be enabled.
    ansible_ssh_pipelining: false
  roles:
    - { role: kargo-defaults}
    - { role: bootstrap-os, tags: bootstrap-os}

- hosts: temp
  remote_user: vagrant
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    ansible_ssh_pipelining: true
  gather_facts: true

- hosts: temp
  remote_user: vagrant
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kargo-defaults}
    - { role: kernel-upgrade, tags: kernel-upgrade, when: kernel_upgrade is defined and kernel_upgrade }
    - { role: kubernetes/preinstall, tags: preinstall }
    - { role: docker, tags: docker }


